build:
	g++ main.cpp ../glad/src/glad.c -o OpenGL_glad_integ -lGL -lGLU -lglut -lGLEW -lglfw -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor

run:
	./OpenGL_glad_integ

clean:
	rm OpenGL_glad_integ